name: build-n-deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/"
          target: ${{ secrets.SSH_TARGET }}


#      - name: Deploy
#        uses: easingthemes/ssh-deploy@main
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          ARGS: '-azvp --del'
#          SOURCE: "build/"
#          REMOTE_HOST: ${{ secrets.SSH_HOST }}
#          REMOTE_USER: ${{ secrets.SSH_USER }}
#          REMOTE_PORT: ${{ secrets.SSH_PORT }}
#          TARGET: ${{ secrets.SSH_TARGET }}
